name: "Run Tests"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Retrieve Rust version
        id: rust-version
        run: echo "rust-version=$(grep '^rust ' .tool-versions | awk '{print $2}')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Set up Rust tool chain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ steps.rust-version.outputs.rust-version }}

      - name: Add wasm32-wasi target
        run: rustup target add wasm32-wasip1

      - name: Setup Viceroy
        run: cargo install viceroy

      - name: Run tests
        run: cargo test
